version: '3'

services:

  app:
    build:
      context: nodejs
    container_name: app
    hostname: app
    networks:
      - nginxnet
    tty: true
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80" 
    depends_on:
      - app
    networks:
      - nginxnet


  db:
    image: arm64v8/mysql:oracle
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginxnet
    healthcheck:
        test: ["CMD", "curl", "-f", "http://db:3306"]
        interval: 20s
        timeout: 20s
        retries: 5

networks:
  nginxnet:
    driver: bridge